### ISSUE TITLE
about transplant

### ISSUE THREAD

**Issue by zruibin** [yoyofr/iFBA#1]
this project how to transplant?my project will using you code(fba_src),I join you code into my project,but always raise warning,there is must to setting the build setting?can you tell me how to using you sources code for transplant,thanks!

**Comment by yoyofr** [comment]
Hi,

Sorry but I cannot understand well enough your email. Is it automated
translation ?

rgds,
ym

2013/12/12 Ruibin.Chow notifications@github.com

**Comment by zruibin** [comment]
Pardon me,my english was bad.
I using you code(fba_src) at my project,but it always prompt warning, it was must to setting the build environment before using you code? Or???
Could you give me you email, I have some detail question about this project asking you.
Thanks!
